---
-
  name: Initial setup
  hosts: localhost
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/nvim-setup.yml

